version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
  eviltraps:
    container_name: eviltraps
    image: "docker.pkg.github.com/trikolon/evil-traps/eviltraps:master"
    restart: always
    environment:
      - VIRTUAL_HOST=eviltrap.site,*.eviltrap.site
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=eviltrap.site,www.eviltrap.site,1.eviltrap.site,2.eviltrap.site,3.eviltrap.site,4.eviltrap.site,5.eviltrap.site
      - LETSENCRYPT_EMAIL=mail@eviltrap.site

volumes:
  conf.d:
  vhost.d:
  html:
  certs:
  htpasswd:
